Edge & Chrome addon: Move to blank page on redirect from sub frames
ThinBridge/ThinBridge pull request #90
Opened 2024-07-03 02:51 UTC by ashie

# Which issue(s) this PR fixes:

N/A

# What this PR does / why we need it:

We observed that CANCEL_REQUEST from sub frames causes unexpected moving back on parent main frame. To avoid it, just move to a blank page at sub frames.

# How to verify the fixed issue:

Check sub-frame's behaviour with enabling redirect on sub-frame.

## The steps to verify:

* put the following config to C:\Program Files\ThinBridge\ThinBridgeBHO.ini
```
[GLOBAL]
@DISABLED
@TRUSTED_ZONE
@RDP_APPMODE
@DISABLE_IE_DDE

[Chrome]
@BROWSER_PATH:
@DISABLED
@REDIRECT_PAGE_ACTION:0
@CLOSE_TIMEOUT:3

[Edge]
@BROWSER_PATH:
@REDIRECT_PAGE_ACTION:0
@CLOSE_TIMEOUT:3

[Default]
@BROWSER_PATH:Chrome
@REDIRECT_PAGE_ACTION:0
@CLOSE_TIMEOUT:3

[CUSTOM18]
@BROWSER_PATH:
@REDIRECT_PAGE_ACTION:0
@CLOSE_TIMEOUT:3
*://www.fluentd.org/*
*://platform.twitter.com/*
```
* Open new tab on Edge
* Enter `https://www.fluentd.org` to location entry.

## Expected result:

* The URL `https://www.youtube.com/embed/sIVGsQgMHIo` in sub-frame is redirected to Chrome.
* The sub-frame transients to a blank page.
* The parent main frame doesn't move back to newtab:// (stay in https://www.fluentd.org).

2024-07-04 04:14 UTC, HashidaTKS commented
単純な質問なのですが、 https://github.com/ThinBridge/ThinBridge/blob/db85457c70ee1cb0d43f286d2d4aa9984eee18d7/webextensions/chrome/background.js#L447 で同様の対処は不要なのでしょうか？
名前から察するに`onTabUpdated` はサブフレームに対しては呼ばれなさそうなのですが、確信がないです。

2024-07-04 04:29 UTC, piroor commented
onTabUpdatedは、実際の読み込み先がトップレベルのフレームかサブフレームかを問わず「タブの状態が変更されたとき」に呼ばれます。
URLはそのタブの「トップレベルのフレームのURL」が処理対象となり、その後のscripting.executeScriptは「そのタブのトップレベルのコンテンツ」に対して実行されます。
なので、サブフレームの内容に対しては発動し得ないと思われます。

2024-07-04 04:30 UTC, ashie commented
> なので、サブフレームの内容に対しては発動し得ないと思われます。

はい、サブフレームに対しては発動しないです。

2024-07-04 04:34 UTC, HashidaTKS commented
なるほど、`onTabUpdated`が呼ばれるタイミングについては私の認識と違いましたが、結果的にサブフレームに対しては実行されないということで承知しました。ありがとうございます。

2024-07-04 08:14 UTC, piroor requested changes
この変更内容自体は問題無いと思います。
この変更によって修正される動作の検証手順をリリース前検証手順に追加して頂くことは可能でしょうか？

2024-07-04 08:48 UTC, HashidaTKS commented
変更内容に問題ないと思います。

2024-07-05 06:54 UTC, ashie commented
これ、なぜメインフレームに対して発動してしまうのかと言うと、多くの場合サブフレームで開く初期URLに対してリダイレクトが発動するので戻るページが存在しないためであると考えられる。ブラウザの「戻る」ボタンも、iframe内に戻る対象がある場合はiframe内に対してのみ聞くが、iframe内が初期ページまで戻るとメインフレームに対して効くという挙動になる。これと同じ。

実際、iframe内の初期URLをリダイレクト対象ではないページにし、そこにリダイレクト対象となるリンクを入れておいて
現行版（本PR適用前）にて検証したところ、メインフレームは戻らずサブレフーム内は期待通り元のページで維持される（一瞬遷移した後に戻る）という結果となった。

このため`CANCE_REQUEST`の作りをもう少し頑張れば、サブフレーム内を元のページに留めるように改修できる可能性はある。ただし、もし検出に失敗した場合は誤ってメインフレーム側が戻る問題が再発する可能性もあり、万が一それが起こってしまった場合の方がデメリットが大きいので、このPRでは安全側に倒して単純に空白ページに遷移するのみにしている。いったんこれをマージした後、もう少し頑張れるかどうかは後でまた検討する予定。

2024-07-10 00:18 UTC, ashie commented
> この変更内容自体は問題無いと思います。 この変更によって修正される動作の検証手順をリリース前検証手順に追加して頂くことは可能でしょうか？

追加しました。

2024-07-10 00:35 UTC, ashie commented
> これ、なぜメインフレームに対して発動してしまうのかと言うと、多くの場合サブフレームで開く初期URLに対してリダイレクトが発動するので戻るページが存在しないためであると考えられる。

この点をコメントに追記した。

2024-07-10 00:52 UTC, piroor approved these changes
It looks good to merge.

2024-07-10 00:52 UTC, merged