Improve keeping existing tab and closing empty tab
ThinBridge/ThinBridge pull request #94
Opened 2024-07-09 13:50 UTC by ashie

# Which issue(s) this PR fixes:

N/A.

# What this PR does / why we need it:

v2.2.1 sometimes fails to keep existing tab or close empty tab after redirect to another browser.
This patch tries to fix these issues.

* Existing tabs before installing this add-on should be kept as known tabs.
* Prevent known tabs from being closed by `onTabUpdated()` (although I'm not sure it's really possible).
* Add `await` to `close.tabs.remove()` to ensure to wait closing a specified tab.

# How to verify the fixed issue:

TBD

## The steps to verify:

TBD

## Expected result:

TBD

2024-07-10 01:31 UTC, ashie commented
`3. Add await to close.tabs.remove() to ensure to wait closing a specified tab.`

I've tried many times and I confirmed that this issue never reproduced at lease in this term.
Before this fix, it's reproduced about once every few dozen times.

2024-07-10 02:16 UTC, piroor requested changes
コメントしました

2024-07-10 02:16 UTC, piroor commented on webextensions/chrome/background.js
> +    if (this.knownTabIds.has(tabId))
この変更の経緯を把握していれば疑問には感じないのですが、経緯を忘れた状態で見ると、「なぜhasで確認した後にaddしているのだろう？」のように混乱しそうな気がしています。
letで定義した後で変更するのではなく、
`const isClosableTab = this.newTabIds.has(tabId) && !this.knownTabIds.has(tabId)`
とした上で、`we should not close tabs already opened at this extension is loaded`のようなコメントを加えるのはどうでしょうか？

2024-07-10 02:19 UTC, ashie commented on webextensions/chrome/background.js
> +    if (this.knownTabIds.has(tabId))
`const isClosableTab = this.newTabIds.has(tabId) && !this.knownTabIds.has(tabId)`

これじゃ駄目な気がしているのでこういう形になってます。
`this.knownTabIds.has(tabId)`のときは閉じないのが確定なのですが、`!this.knownTabIds.has(tabId)`で閉じるの確定かと言うと...

2024-07-10 02:26 UTC, piroor requested changes

2024-07-10 02:26 UTC, piroor commented on webextensions/chrome/background.js
> +    if (this.knownTabIds.has(tabId))
letで初期値を決めてからあとでifで判断した結果を優先する、という風に分けないといけない場面は実際あると思うのですが、今回のケースでは、この2つ（今のコードと自分が提案したコード）は論理的には等価です。

2024-07-10 02:26 UTC, piroor commented
コメントを追加しようとしたら新規のレビューコメントになってしまいました。すみません。

2024-07-10 02:32 UTC, HashidaTKS commented on webextensions/chrome/background.js
> +    if (this.knownTabIds.has(tabId))
私も結城さんのコードは論理的に等価と思いました。
（どちらも以下のマトリックスになりました。）

|this.newTabIds.has(tabId)|this.knownTabIds.has(tabId)|isClosableTab|
|--|--|--|
|true|true|false|
|true|false|true|
|false|true|false|
|false|false|false|

2024-07-10 02:34 UTC, piroor commented on webextensions/chrome/background.js
> +    if (this.knownTabIds.has(tabId))
逆に言うと、足永さんが懸念されている点（自分はまだそこがピンと来ていなくて、コードだけ見ていた）が元のコードでは解決できていないということなのかもしれません。

2024-07-10 02:34 UTC, ashie commented on webextensions/chrome/background.js
> +    if (this.knownTabIds.has(tabId))
ですよねぇ...何を懸念してたんだか

2024-07-10 03:10 UTC, ashie commented on webextensions/chrome/background.js
> +    if (this.knownTabIds.has(tabId))
改めて懸念していたことを思い出そうとしましたが、コミットメッセージもtypoしてるし（修正してforce push済み）寝ぼけていただけだろうという結論になりましたので、ご指摘の通り修正しました。

2024-07-10 03:21 UTC, HashidaTKS commented
コードの変更内容は問題ないように思いました。

2024-07-10 03:29 UTC, ashie commented
> この変更で変わる動作について、リリース前検証手順を追加して頂くことは可能でしょうか？

これを毎回テストするか？アドオンインストールし直しという比較的面倒なテスト工数が増えるのに見合うだけの価値があるか？というところに迷いがあったので、相談してから決めようと思ってまだ追加してませんでしたが、アップデート直後に継続して使い続けることは普通に起こり得る（運用でカバーしきれない）し、開いてたタブが意図せず閉じるのはダメージがそれなりに大きいので、やっぱりあった方が良いか。

2024-07-10 04:36 UTC, piroor commented
拡張機能の更新以外に、関連付けからの起動でも影響がありそうな気がします。
検証手順としては、

1. 拡張機能の強制インストール状態を解除（GPOの設定を一時的に無効化）
2. タブを開く
3. GPOの設定を変更して拡張機能を再度強制インストール

とすると、「拡張機能を更新する」という部分を再現しないでも、検証したい箇所の動作を確かめられるのではないかと思います。どうでしょうか。

2024-07-10 06:03 UTC, ashie commented
検証手順追加しました。

2024-07-10 06:41 UTC, HashidaTKS commented on doc/verify/PreReleaseVerification.md
> +5. GPOでインストールした拡張機能を再度インストールする。
このタイミングで一度Edgeを再起動してタブを開きなおさなくて大丈夫でしょうか？

一度アンインストールされた時点でキャッシュもリセットされると思いますので、現在の手順でも問題ないのではないかと思っているのですが、念のため確認です。

2024-07-10 06:43 UTC, ashie commented on doc/verify/PreReleaseVerification.md
> +5. GPOでインストールした拡張機能を再度インストールする。
これ、むしろ再起動しないでもちゃんと動くようにするための修正であり、そのテストなんですよ。

2024-07-10 06:45 UTC, ashie commented on doc/verify/PreReleaseVerification.md
> +5. GPOでインストールした拡張機能を再度インストールする。
なので再起動しちゃうと今回の修正のためのテストにならない。

2024-07-10 07:02 UTC, HashidaTKS commented on doc/verify/PreReleaseVerification.md
> +5. GPOでインストールした拡張機能を再度インストールする。
```suggestion
5. GPOでアンインストールした拡張機能を再度インストールする。
```

2024-07-10 07:06 UTC, ashie commented on doc/verify/PreReleaseVerification.md
> +5. GPOでインストールした拡張機能を再度インストールする。
あざっす。修正しました。

2024-07-10 07:08 UTC, HashidaTKS approved these changes
私は問題ないと思いました。

2024-07-11 01:35 UTC, piroor requested changes

2024-07-11 01:35 UTC, piroor commented on doc/verify/PreReleaseVerification.md
> +6. アドレスバーに https://www.google.com を入力し、Enterする。
5と6の間で、それ以上の明示的なそうさが無くても自動的にhandleStartupでのリダイレクト処理が動いているはずで、それについても「期待される結果」があったほうが良いのではと思いますが、どうでしょうか？

また、「アドオンインストール前から存在する既存タブでの挙動」という見出しに対して、ここではインストール後に新しいタブを追加で開いているので、違和感があります。「こういう動作を検証するため」という補足情報を足して頂くことは可能でしょうか？

2024-07-11 01:44 UTC, ashie commented on doc/verify/PreReleaseVerification.md
> +6. アドレスバーに https://www.google.com を入力し、Enterする。
> 「アドオンインストール前から存在する既存タブでの挙動」という見出しに対して、ここではインストール後に新しいタブを追加で開いているので、違和感があります。

追加で開いていないつもりなので、その旨を記載した方が良いですかね。
「2.で開いたタブをアクティブにし...」とか

2024-07-11 01:49 UTC, piroor commented on doc/verify/PreReleaseVerification.md
> +6. アドレスバーに https://www.google.com を入力し、Enterする。
なるほど、そういう意味でしたか！ 確かに「2で開いたタブに」と明記してあれば誤解は減りそうです。

2024-07-11 02:21 UTC, ashie commented on doc/verify/PreReleaseVerification.md
> +6. アドレスバーに https://www.google.com を入力し、Enterする。
> 5と6の間で、それ以上の明示的な操作が無くても自動的にhandleStartupでのリダイレクト処理が動いているはずで、それについても「期待される結果」があったほうが良いのではと思いますが、どうでしょうか？

以下のように書こうとしてみましたが、見た目上何も起こらないのが期待値なので、改めて書くのも微妙な感じがします。
```
   4. アドオン再インストール後の既存タブの挙動を確認する。
     * 期待される結果：
       * 2.で開いた新規タブが維持されている。
```

2024-07-11 02:35 UTC, ashie commented on doc/verify/PreReleaseVerification.md
> +6. アドレスバーに https://www.google.com を入力し、Enterする。
> なるほど、そういう意味でしたか！ 確かに「2で開いたタブに」と明記してあれば誤解は減りそうです。

というわけでひとまずこの修正だけ入れました。

2024-07-11 02:53 UTC, piroor commented on doc/verify/PreReleaseVerification.md
> +6. アドレスバーに https://www.google.com を入力し、Enterする。
他の検証項目で「ThinBridgeによるリダイレクトが発生しない。」のように「何も起こらないこと」を期待値としている物はすでにあるので、改めて書いて問題無いのではと自分は思っています。

* 2で開いたタブが閉じられていない。
* 2で開いたタブのURLがChromeで新たに開かれていない。

を確認するのはどうでしょうか？

2024-07-11 02:59 UTC, ashie commented on doc/verify/PreReleaseVerification.md
> +6. アドレスバーに https://www.google.com を入力し、Enterする。
そのように期待値の項目を追加しました。

2024-07-11 03:04 UTC, piroor approved these changes
自分が懸念していたてんは解消されました。ご対応ありがとうございます！

2024-07-11 03:04 UTC, merged